### ISSUE TITLE
Can a release tag or version be created?

### ISSUE THREAD

**Issue by herbygillot** [amit-davidson/Chronos#11]
Would like to package Chronos but there are no releases or version tags currently.

**Comment by amit-davidson** [comment]
Sure, I'll fix the versioning.

**Comment by amit-davidson** [comment]
@herbygillot Done. https://github.com/amit-davidson/Chronos/releases/tag/v.0.1.0
Mind that the static code of analysis part of Chronos doesn't support all the language features. You can look in the release notes (and in the README as well) and see what is supported.

**Comment by herbygillot** [comment]
Thank you @amit-davidson
