### ISSUE TITLE
Go get instructions won't work

### ISSUE THREAD

**Issue by dcu** [amit-davidson/Chronos#4]
The username on github is the wrong one, and even fixing it won't product the expected binary name

**Comment by amit-davidson** [comment]
You're right. I switched the account name and forgot to update the readme. About the binary name, using the -o flag creates the binary with the correct name. What do you mean that it's not creating the expected binary name?

**Comment by dcu** [comment]
this fix won't work I believe because the binary code is in cmd

**Comment by amit-davidson** [comment]
@dcu Not sure I understand. The fix is for downloading the package, not the binary.
What it that a problem that the main is inside cmd?

**Comment by dcu** [comment]
```
> go get -u -v github.com/amit-davidson/Chronos
github.com/amit-davidson/Chronos (download)
package github.com/amit-davidson/Chronos: no Go files in /Users/dcuadrado/go/src/github.com/amit-davidson/Chronos
```

and

```
[/p/tmp]─> go get -u github.com/amit-davidson/Chronos/cmd
[/p/tmp]─> Chronos
Exception: exec: "Chronos": executable file not found in $PATH
[tty 8], line 1: Chronos
[/p/tmp]─> cmd
Please provide a file to load
```
