### ISSUE TITLE
Could Chronos detect one arbitrary go file？

### ISSUE THREAD

**Issue by ChenhuaYang** [amit-davidson/Chronos#43]
Chrono privide such way to use.
`$ chronos --file <path_to_main> --mod <path_to_module>`

Why should I specify path_to_main, could I just detect one  arbitrary go file, like:
`$ go run -race mysrc.go`

**Comment by amit-davidson** [comment]
When using `go run`, you still have to point to the main function to specify the entry point so it's not really different from Chronos. It also needs the entry point so it can understand the flows of the programs.

**Comment by ChenhuaYang** [comment]
Thanks Amit!

**Comment by amit-davidson** [comment]
:)
