### ISSUE TITLE
golangci-lint

### ISSUE THREAD

**Issue by jerome-laforge** [amit-davidson/Chronos#45]
Is it possible to be more friendly with golangci-lint with https://golangci-lint.run/contributing/new-linters/?

**Comment by ayushr2** [comment]
See https://golang.org/doc/effective_go#package-names for package names and file names.

**Comment by ayushr2** [comment]
The codebase seems to be using CamelCase for file names and package names.

**Comment by amit-davidson** [comment]
@ayushr2 It is, but it's not related. Chronos isn't friendly with golangci-lint as it doesn't support the go/analysis package. 
Supporting it is possible but too complex. More importantly, Chronos was written for learning purposes and isn't suitable for production use. Therefore, I don't recommend including it in golangci-lint

**Comment by jerome-laforge** [comment]
Thanks @amit-davidson for this information.
