### ISSUE TITLE
golang pointer analysis

### ISSUE THREAD

**Issue by scott-cotton** [amit-davidson/Chronos#46]
@amit-davidson Was wondering if updates w.r.t. Golang pointer analysis would be interesting for this project?  Note there has been a fix recently (eg https://github.com/golang/go/issues/45735) and also I am working on (still pre-alpha: https://github.com/go-air/pal)

Would you be interested in seeing if either of these could help this project?

**Comment by amit-davidson** [comment]
The pointer analysis package has been a pain in the ass as it has many bugs and doesn't really work the way you would expect it to work. This project will benefit from a better pointer analysis, but I don't intend to maintain or change the code as it was written for learning purposes.

If you want, you can fork it and replace the pointer analysis package with yours. If that's ok with you, you can reach me through email, and I'll help you with everything you'll need 😀
